### ISSUE TITLE
Cannot read property 's' of undefined when trying to connect to server

### ISSUE THREAD

**Issue by Grimtin10** [m-byte918/MultiOgarII#1540] opened 2020-05-17 04:32 UTC
Whenever I try to connect to my MultiOgar server, in the agario console it gives me this error:
`js__$Boot_HaxeError {val: TypeError: Cannot read property 's' of undefined
    at https://agar.io/mc/agario.js?v=c7a62424a0f4…, message: "TypeError: Cannot read property 's' of undefined", stack: "Error: TypeError: Cannot read property 's' of unde…o/bundle_commons.0d85e89d1b15f5e4c179.js:6:44217)"}
message: "TypeError: Cannot read property 's' of undefined"`
I have absolutely no clue what this means.
Any help would be great.

**Comment by Tombez** [comment] 2020-05-26 09:20
Duplicate of #1531.

**Closed by Tombez** 2020-05-26 09:20 UTC
